/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biodataorganisasi;

import java.awt.Font;

/**
 *
 * @author LABPUSAT
 */
public class BiodataOrganisasiUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public BiodataOrganisasiUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAtas = new javax.swing.JPanel();
        jComboBoxPekerjaan = new javax.swing.JComboBox();
        jTextFieldAlamat = new javax.swing.JTextField();
        jLabelNama = new javax.swing.JLabel();
        jLabelAlamat = new javax.swing.JLabel();
        jLabelPekerjaan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonLaki_Laki = new javax.swing.JRadioButton();
        jRadioButtonPerempuan = new javax.swing.JRadioButton();
        jTextFieldNama = new javax.swing.JTextField();
        jPanelTengahMerah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxCetakTebal = new javax.swing.JCheckBox();
        jCheckBoxCetakMiring = new javax.swing.JCheckBox();
        jButtonTampilkan = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hasilTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAtas.setBackground(new java.awt.Color(204, 255, 204));

        jComboBoxPekerjaan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PNS", "TNI", "Karyawan" }));

        jTextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamatActionPerformed(evt);
            }
        });

        jLabelNama.setText("Nama");
        jLabelNama.setToolTipText("");

        jLabelAlamat.setText("Alamat");

        jLabelPekerjaan.setText("Pekerjaan");

        jLabel1.setText("Jenis Kelamin");

        jRadioButtonLaki_Laki.setBackground(jPanelAtas.getBackground());
        jRadioButtonLaki_Laki.setText("Laki-Laki");
        jRadioButtonLaki_Laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLaki_LakiActionPerformed(evt);
            }
        });

        jRadioButtonPerempuan.setBackground(jPanelAtas.getBackground());
        jRadioButtonPerempuan.setText("Perempuan");
        jRadioButtonPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPerempuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAtasLayout = new javax.swing.GroupLayout(jPanelAtas);
        jPanelAtas.setLayout(jPanelAtasLayout);
        jPanelAtasLayout.setHorizontalGroup(
            jPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNama)
                    .addComponent(jLabelAlamat)
                    .addComponent(jLabelPekerjaan)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(jPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(jPanelAtasLayout.createSequentialGroup()
                        .addComponent(jRadioButtonLaki_Laki)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPerempuan))
                    .addComponent(jTextFieldNama))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAtasLayout.setVerticalGroup(
            jPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlamat))
                .addGap(13, 13, 13)
                .addGroup(jPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPekerjaan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonLaki_Laki)
                    .addComponent(jRadioButtonPerempuan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTengahMerah.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setText("Cetak Tebal");

        jLabel3.setText("Cetak Miring");

        jCheckBoxCetakTebal.setBackground(jPanelTengahMerah.getBackground());
        jCheckBoxCetakTebal.setText("Ya");
        jCheckBoxCetakTebal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCetakTebalActionPerformed(evt);
            }
        });

        jCheckBoxCetakMiring.setBackground(jPanelTengahMerah.getBackground());
        jCheckBoxCetakMiring.setText("Ya");
        jCheckBoxCetakMiring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCetakMiringActionPerformed(evt);
            }
        });

        jButtonTampilkan.setText("Tampilkan");
        jButtonTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTampilkanActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTengahMerahLayout = new javax.swing.GroupLayout(jPanelTengahMerah);
        jPanelTengahMerah.setLayout(jPanelTengahMerahLayout);
        jPanelTengahMerahLayout.setHorizontalGroup(
            jPanelTengahMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTengahMerahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTengahMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTengahMerahLayout.createSequentialGroup()
                        .addComponent(jButtonTampilkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExit))
                    .addGroup(jPanelTengahMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTengahMerahLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxCetakTebal))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTengahMerahLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBoxCetakMiring))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTengahMerahLayout.setVerticalGroup(
            jPanelTengahMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTengahMerahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTengahMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBoxCetakTebal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTengahMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBoxCetakMiring))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanelTengahMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTampilkan)
                    .addComponent(jButtonHapus)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonExit))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        hasilTextArea.setColumns(20);
        hasilTextArea.setRows(5);
        hasilTextArea.setText("\n");
        jScrollPane3.setViewportView(hasilTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTengahMerah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTengahMerah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamatActionPerformed

    private void jRadioButtonLaki_LakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLaki_LakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLaki_LakiActionPerformed

    private void jRadioButtonPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPerempuanActionPerformed

    private void jCheckBoxCetakTebalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCetakTebalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCetakTebalActionPerformed

    private void jCheckBoxCetakMiringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCetakMiringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCetakMiringActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTampilkanActionPerformed
        String Nama, Alamat, Pekerjaan, JenisKelamin;
        Nama = jTextFieldNama.getText();
        Alamat = jTextFieldAlamat.getText();
        Pekerjaan = jComboBoxPekerjaan.getSelectedItem().toString();
        JenisKelamin = jRadioButtonLaki_Laki.getActionCommand();
        
        Font tebal = new Font("Arial", Font.BOLD, 12);
        Font miring = new Font("Arial", Font.ITALIC, 12);
        
        if (jCheckBoxCetakTebal.isSelected()){
            hasilTextArea.setFont(tebal);
        }else if (jCheckBoxCetakMiring.isSelected()){
            hasilTextArea.setFont(miring);
        }
        
        hasilTextArea.setText(
                "Nama = " + Nama + "\n" +
                "Alamat = " + Alamat + "\n" +
                "Pekerjaan = " + Pekerjaan + "\n" +
                "Jenis Kelamin = " + JenisKelamin + "\n"
        );
              
        
    }//GEN-LAST:event_jButtonTampilkanActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed

    }//GEN-LAST:event_jButtonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataOrganisasiUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea hasilTextArea;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonTampilkan;
    private javax.swing.JCheckBox jCheckBoxCetakMiring;
    private javax.swing.JCheckBox jCheckBoxCetakTebal;
    private javax.swing.JComboBox jComboBoxPekerjaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelPekerjaan;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAtas;
    private javax.swing.JPanel jPanelTengahMerah;
    private javax.swing.JRadioButton jRadioButtonLaki_Laki;
    private javax.swing.JRadioButton jRadioButtonPerempuan;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
